version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-storage}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ENVIRONMENT: ${ENVIRONMENT:- dev}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT:- 5432}
      POSTGRES_USER: ${POSTGRES_USER:- postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:- postgres}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE:- storage}
      JWT_SECRET: ${JWT_SECRET:- secret}

    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - backend


networks:
  backend:

volumes:
  postgres: